language: vim

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/vim'
    packages:
      - vim

before_script: scripts/install-ci.sh

script: scripts/test-ci.sh

notifications:
  email: false
